name: Mostrar usuário do push

on:
  push:
    branches:
      - main

jobs:
  usuario:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar usuário que fez o push
        run: echo "Usuário do push = ${{ github.actor }}"
