name: Contar arquivos toda meia-noite

on:
  schedule:
    - cron: "0 0 * * *" # 00:00 UTC = 21:00 no horário de Brasília

permissions:
  contents: write

jobs:
  contar-arquivos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Contar arquivos
        run: |
          echo "Contagem automática - $(date)" > contagem.txt
          echo "HTML: $(find . -name '*.html' | wc -l)" >> contagem.txt
          echo "CSS: $(find . -name '*.css' | wc -l)" >> contagem.txt
          echo "JS: $(find . -name '*.js' | wc -l)" >> contagem.txt

      - name: Commit e push do arquivo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add contagem.txt
          git commit -m "Atualiza contagem automática - $(date)"
          git push
